### ISSUE TITLE
Does not parse ES2015 functions properly

### ISSUE THREAD

**Issue by cmtt** [cmtt/gulp-di#1]
Please see [this issue](https://github.com/tunnckoCore/parse-function/issues/2):

> Gulp can be used in conjunction with ES2015 code in two ways:

> 1. Writing ES2015+ code - the "gulpfile.js" would be written in ES2015+, as Node.js supports already a subset of the new standard.

> 2. Writing ES2015+ code using the "[Babel](http://babeljs.io)" transpiler - the "gulpfile.babel.js" and all imported modules would be transpiled back to ES5 code. In this case, parse-function would work as intended.

It would be also possible to make use of a JavaScript parser like esprima or acorn.

**Comment by cmtt** [comment]
Thanks to @tunnckoCore, this bug has been fixed :+1:

**Comment by tunnckoCore** [comment]
Haha, thanks! You can review `v2.3.0` and say what you think. :)

Some short info:
- `v2.3.0` uses acorn
- `v2.3.0` is 2-5x slower  than `v2.2.2`
- `v2.2.2` uses "regex matching" approach
- `v2.2.2` is 40-60x faster than all previous `v2.2.x` version which uses "string looping" approach

I cant benchmarks between `v2.0.1` and `v2.2.2` and `v2.3.x`, but i think it's at least the same as `v2.2.2`
