### ISSUE TITLE
tweaks

### ISSUE THREAD

**Issue by tunnckoCore** [cmtt/gulp-di#4]
[contrib/help.js#L65-L70](https://github.com/cmtt/gulp-di/blob/8fd8be2b7c1c5c7196ef27bfcd2ccafef330936e/contrib/help.js#L65-L70) it's always `object` and why [lib/di.js#L283-L284](https://github.com/cmtt/gulp-di/blob/master/lib/di.js#L283-L284) is needed?

**Comment by cmtt** [comment]
Hello tunnckoCore,

thank you for the heads up. These checks are not necessary at this stage. Both are an rather an expression of an attempt to prevent unforeseen circumstances (especially with regard to dependencies which might introduce breaking changes).

As long as _parse-function_ guarantees returning an object with a "arguments" member, these lines can be simplified.

**Comment by tunnckoCore** [comment]
> As long as parse-function guarantees returning an object with a "arguments" member, these lines can be simplified.

yep, that's the idea. will stay like that forever. and basically there's no breaking changes between 2.0 and 2.3, so yea. forever. we need it like that.
